In [198]:
import pandas as pd
import numpy as np

In [46]:
cols=['Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age','Outcome']

In [47]:
pdf=pd.read_csv("pima-indians-diabetes.data",names=cols)

In [48]:
pdf.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [49]:
from sklearn.model_selection import train_test_split

In [50]:
X=pdf.drop('Outcome',axis=1)

In [51]:
y=pdf['Outcome']

In [52]:
print(X.shape)
print(y.shape)

print(X.columns)

(768, 8)
(768,)
Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age'],
      dtype='object')


In [53]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=1)

In [54]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(537, 8)
(231, 8)
(537,)
(231,)


In [55]:
X_train.head(2)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
88            15      136             70             32      110  37.1   
467            0       97             64             36      100  36.8   

     DiabetesPedigreeFunction  Age  
88                      0.153   43  
467                     0.600   25

In [56]:
X_test.head(2)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
285            7      136             74             26      135  26.0   
101            1      151             60              0        0  26.1   

     DiabetesPedigreeFunction  Age  
285                     0.647   51  
101                     0.179   22

In [57]:
y_train.head(2)

88     1
467    0
Name: Outcome, dtype: int64

In [58]:
y_test.head(2)

285    0
101    0
Name: Outcome, dtype: int64

## 1 --> Standard Scaler 

In [68]:
##Fit and Transform on Train Data,on X_test only transform bcz of Data Leakage

from sklearn.preprocessing import StandardScaler  
scaler = StandardScaler()  
scaler.fit(X_train)

X_train = scaler.transform(X_train)  
X_test = scaler.transform(X_test)  

In [65]:
type(X_train)

numpy.ndarray

In [67]:
X_train[1]

array([-1.12101735, -0.76891126, -0.2463932 ,  1.03229735,  0.19979565,
        0.64699564,  0.39612987, -0.69526203])

In [69]:
X_test[1]

array([-0.82270897,  0.96100484, -0.44543516, -1.2257217 , -0.68822177,
       -0.74843705, -0.86878331, -0.94617312])

## 2 --> Get Dummies

In [85]:
import pandas as pd

In [124]:
data=[[1 , 'male' , 28 , 'Patna'],[2 , 'female' , 29 , 'bangalore'],[3 , 'male' , 38 , 'Pune'],
      [4 , 'female' , 32 , 'Patna']]

In [125]:
Mydf=pd.DataFrame(data=data,columns=['Id','Sex','Age','City'])

In [126]:
Mydf

Id     Sex  Age       City
0   1    male   28      Patna
1   2  female   29  bangalore
2   3    male   38       Pune
3   4  female   32      Patna

In [127]:
one_hot_encoding=pd.get_dummies(Mydf)

In [128]:
one_hot_encoding

Id  Age  Sex_female  Sex_male  City_Patna  City_Pune  City_bangalore
0   1   28           0         1           1          0               0
1   2   29           1         0           0          0               1
2   3   38           0         1           0          1               0
3   4   32           1         0           1          0               0

In [129]:
one_hot_encoding_specific_col=pd.get_dummies(Mydf,columns=['City'])

In [130]:
one_hot_encoding_specific_col

Id     Sex  Age  City_Patna  City_Pune  City_bangalore
0   1    male   28           1          0               0
1   2  female   29           0          0               1
2   3    male   38           0          1               0
3   4  female   32           1          0               0

## 3 --> Label Encoder

In [132]:
import pandas as pd

In [133]:
data=[[1 , 'male' , 28 , 'short'],[2 , 'female' , 29 , 'medium'],[3 , 'male' , 38 , 'tall'],
      [4 , 'female' , 32 , 'short']]

In [134]:
data

[[1, 'male', 28, 'short'],
 [2, 'female', 29, 'medium'],
 [3, 'male', 38, 'tall'],
 [4, 'female', 32, 'short']]

In [135]:
Le_DF=pd.DataFrame(data,columns=['Id','Sex','Age','Height'])

In [136]:
Le_DF

Id     Sex  Age  Height
0   1    male   28   short
1   2  female   29  medium
2   3    male   38    tall
3   4  female   32   short

In [137]:
Le_DF['Height'].unique()

array(['short', 'medium', 'tall'], dtype=object)

In [138]:
from sklearn import preprocessing

In [139]:
LabelEncoder=preprocessing.LabelEncoder()

In [140]:
Le_DF['Height']= LabelEncoder.fit_transform(Le_DF['Height'])

In [141]:
Le_DF['Height'].unique()

array([1, 0, 2])

## 4 --> Combining a Dataframe

In [155]:
Data_L1=[['Swanns Way', 29 , 'Paris'],['Suitable Boy' , 20 , 'Purani Delhi'],
             ['Love In the Time Of Cholera' ,68 , 'Medellin'],
             ['Gone With the Wind' , 00 , 'Miami']]

In [159]:
Books_Coffe_Shop_Part1=pd.DataFrame(Data_L1,columns=['Books','Zip','Place_To_Read_This_Book'])

In [160]:
Books_Coffe_Shop_Part1

Books  Zip Place_To_Read_This_Book
0                   Swanns Way   29                   Paris
1                 Suitable Boy   20            Purani Delhi
2  Love In the Time Of Cholera   68                Medellin
3           Gone With the Wind    0                   Miami

In [161]:
Data_L2= [['Mid Night Children',64,'London'],['Emily_Poems', 29,'Massachusetts'],
       ['wuthering heights',78,'Yorkshire'],
       ['Pride and Prejudice',30,'Edinburg']]

In [162]:
Books_Coffe_Shop_Part2=pd.DataFrame(Data_L2,columns=['Books','Zip','Place_To_Read_This_Book'])

In [164]:
Final_Book_List=pd.concat([Books_Coffe_Shop_Part1,Books_Coffe_Shop_Part2],ignore_index=True)

In [165]:
Final_Book_List

Books  Zip Place_To_Read_This_Book
0                   Swanns Way   29                   Paris
1                 Suitable Boy   20            Purani Delhi
2  Love In the Time Of Cholera   68                Medellin
3           Gone With the Wind    0                   Miami
4           Mid Night Children   64                  London
5                  Emily_Poems   29           Massachusetts
6            wuthering heights   78               Yorkshire
7          Pride and Prejudice   30                Edinburg

In [166]:
Final_Book_List_Column=pd.concat([Books_Coffe_Shop_Part1,Books_Coffe_Shop_Part2],axis=1)

In [167]:
Final_Book_List_Column

Books  Zip Place_To_Read_This_Book  \
0                   Swanns Way   29                   Paris   
1                 Suitable Boy   20            Purani Delhi   
2  Love In the Time Of Cholera   68                Medellin   
3           Gone With the Wind    0                   Miami   

                 Books  Zip Place_To_Read_This_Book  
0   Mid Night Children   64                  London  
1          Emily_Poems   29           Massachusetts  
2    wuthering heights   78               Yorkshire  
3  Pride and Prejudice   30                Edinburg

## 5 --> Merge

In [177]:
Books= [[100,'Mid Night Children','London'],[101,'Emily_Poems','Massachusetts'],
       [102,'wuthering heights','Yorkshire'],
       [103,'Pride and Prejudice','Edinburg']]

In [185]:
Coffee_Along_With =[[103,'Latte','Morning'],[101,'Black Coffee','Evening'],
                   [100,'Caramel Macchiato','Afternoon'],
                   [108,'White Mocha','Night'],
                   [107,'Flat White','Morning'],
                   [110,'Brewed coffee','Evening'],
                   [111,'Caffe Mocha','Night']]

In [186]:
Books_Df=pd.DataFrame(Books,columns=['Zip','Books','Place'])

In [187]:
Books_Df

Zip                Books          Place
0  100   Mid Night Children         London
1  101          Emily_Poems  Massachusetts
2  102    wuthering heights      Yorkshire
3  103  Pride and Prejudice       Edinburg

In [188]:
Coffee_Along_With_Df=pd.DataFrame(Coffee_Along_With,columns=['Zip','Coffee_flavor','Time'])

In [189]:
Coffee_Along_With_Df

Zip      Coffee_flavor       Time
0  103              Latte    Morning
1  101       Black Coffee    Evening
2  100  Caramel Macchiato  Afternoon
3  108        White Mocha      Night
4  107         Flat White    Morning
5  110      Brewed coffee    Evening
6  111        Caffe Mocha      Night

In [190]:
Books_Df.merge(Coffee_Along_With_Df,how='inner')

Zip                Books          Place      Coffee_flavor       Time
0  100   Mid Night Children         London  Caramel Macchiato  Afternoon
1  101          Emily_Poems  Massachusetts       Black Coffee    Evening
2  103  Pride and Prejudice       Edinburg              Latte    Morning

In [191]:
Books_Df.merge(Coffee_Along_With_Df,how='left')

Zip                Books          Place      Coffee_flavor       Time
0  100   Mid Night Children         London  Caramel Macchiato  Afternoon
1  101          Emily_Poems  Massachusetts       Black Coffee    Evening
2  102    wuthering heights      Yorkshire                NaN        NaN
3  103  Pride and Prejudice       Edinburg              Latte    Morning

In [193]:
Books_Df.merge(Coffee_Along_With_Df,how='right')

Zip                Books          Place      Coffee_flavor       Time
0  100   Mid Night Children         London  Caramel Macchiato  Afternoon
1  101          Emily_Poems  Massachusetts       Black Coffee    Evening
2  103  Pride and Prejudice       Edinburg              Latte    Morning
3  108                  NaN            NaN        White Mocha      Night
4  107                  NaN            NaN         Flat White    Morning
5  110                  NaN            NaN      Brewed coffee    Evening
6  111                  NaN            NaN        Caffe Mocha      Night

In [195]:
Books_Df.merge(Coffee_Along_With_Df,how='outer')

Zip                Books          Place      Coffee_flavor       Time
0  100   Mid Night Children         London  Caramel Macchiato  Afternoon
1  101          Emily_Poems  Massachusetts       Black Coffee    Evening
2  102    wuthering heights      Yorkshire                NaN        NaN
3  103  Pride and Prejudice       Edinburg              Latte    Morning
4  108                  NaN            NaN        White Mocha      Night
5  107                  NaN            NaN         Flat White    Morning
6  110                  NaN            NaN      Brewed coffee    Evening
7  111                  NaN            NaN        Caffe Mocha      Night